# HTML
# Archive your static HTML project and save it with the build record.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'
variables:
  phpVersion: 7.2

steps:
- task: ArchiveFiles@2
- script: |
    sudo apt-get update && apt-get install -y unzip
    sudo curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    sudo apt-get -qq install git-ftp
     git ftp init --user "himmel" --passwd "j9vcpPqY!" "ftp://159.65.207.17/public_html/commits"
  displayName: 'Use PHP version $(phpVersion)'
- task: PublishBuildArtifacts@1
